/*
 * Hypto IAM
 * APIs for Hypto IAM Service.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: engineering@hypto.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.hypto.iam.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;

/** CreateSubOrganizationResponse */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class CreateSubOrganizationResponse {
    public static final String SERIALIZED_NAME_SUB_ORGANIZATION = "subOrganization";

    @SerializedName(SERIALIZED_NAME_SUB_ORGANIZATION)
    private SubOrganization subOrganization;

    public CreateSubOrganizationResponse() {}

    public CreateSubOrganizationResponse subOrganization(SubOrganization subOrganization) {

        this.subOrganization = subOrganization;
        return this;
    }

    /**
     * Get subOrganization
     *
     * @return subOrganization
     */
    @javax.annotation.Nonnull
    @ApiModelProperty(required = true, value = "")
    public SubOrganization getSubOrganization() {
        return subOrganization;
    }

    public void setSubOrganization(SubOrganization subOrganization) {
        this.subOrganization = subOrganization;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CreateSubOrganizationResponse createSubOrganizationResponse =
                (CreateSubOrganizationResponse) o;
        return Objects.equals(this.subOrganization, createSubOrganizationResponse.subOrganization);
    }

    @Override
    public int hashCode() {
        return Objects.hash(subOrganization);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class CreateSubOrganizationResponse {\n");
        sb.append("    subOrganization: ").append(toIndentedString(subOrganization)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}
