/*
 * Hypto IAM
 * APIs for Hypto IAM Service.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: engineering@hypto.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.hypto.iam.client.model;


import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;

/** CreateOrganizationResponse */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class CreateOrganizationResponse {
    public static final String SERIALIZED_NAME_ORGANIZATION = "organization";

    @SerializedName(SERIALIZED_NAME_ORGANIZATION)
    private Organization organization;

    public static final String SERIALIZED_NAME_ROOT_USER_TOKEN = "rootUserToken";

    @SerializedName(SERIALIZED_NAME_ROOT_USER_TOKEN)
    private String rootUserToken;

    public CreateOrganizationResponse() {}

    public CreateOrganizationResponse organization(Organization organization) {

        this.organization = organization;
        return this;
    }

    /**
     * Get organization
     *
     * @return organization
     */
    @javax.annotation.Nonnull
    @ApiModelProperty(required = true, value = "")
    public Organization getOrganization() {
        return organization;
    }

    public void setOrganization(Organization organization) {
        this.organization = organization;
    }

    public CreateOrganizationResponse rootUserToken(String rootUserToken) {

        this.rootUserToken = rootUserToken;
        return this;
    }

    /**
     * JWT token of the root user
     *
     * @return rootUserToken
     */
    @javax.annotation.Nonnull
    @ApiModelProperty(required = true, value = "JWT token of the root user")
    public String getRootUserToken() {
        return rootUserToken;
    }

    public void setRootUserToken(String rootUserToken) {
        this.rootUserToken = rootUserToken;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CreateOrganizationResponse createOrganizationResponse = (CreateOrganizationResponse) o;
        return Objects.equals(this.organization, createOrganizationResponse.organization)
                && Objects.equals(this.rootUserToken, createOrganizationResponse.rootUserToken);
    }

    @Override
    public int hashCode() {
        return Objects.hash(organization, rootUserToken);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class CreateOrganizationResponse {\n");
        sb.append("    organization: ").append(toIndentedString(organization)).append("\n");
        sb.append("    rootUserToken: ").append(toIndentedString(rootUserToken)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}
