/*
 * Hypto IAM
 * APIs for Hypto IAM Service.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: engineering@hypto.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.hypto.iam.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/** ListCredentialResponse */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ListCredentialResponse {
    public static final String SERIALIZED_NAME_CREDENTIALS = "credentials";

    @SerializedName(SERIALIZED_NAME_CREDENTIALS)
    private List<CredentialWithoutSecret> credentials = new ArrayList<>();

    public ListCredentialResponse() {}

    public ListCredentialResponse credentials(List<CredentialWithoutSecret> credentials) {

        this.credentials = credentials;
        return this;
    }

    public ListCredentialResponse addCredentialsItem(CredentialWithoutSecret credentialsItem) {
        this.credentials.add(credentialsItem);
        return this;
    }

    /**
     * Get credentials
     *
     * @return credentials
     */
    @javax.annotation.Nonnull
    @ApiModelProperty(required = true, value = "")
    public List<CredentialWithoutSecret> getCredentials() {
        return credentials;
    }

    public void setCredentials(List<CredentialWithoutSecret> credentials) {
        this.credentials = credentials;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ListCredentialResponse listCredentialResponse = (ListCredentialResponse) o;
        return Objects.equals(this.credentials, listCredentialResponse.credentials);
    }

    @Override
    public int hashCode() {
        return Objects.hash(credentials);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ListCredentialResponse {\n");
        sb.append("    credentials: ").append(toIndentedString(credentials)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}
