/*
 * Hypto IAM
 * APIs for Hypto IAM Service.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: engineering@hypto.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.hypto.iam.client.model;


import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/** Payload to update action */
@ApiModel(description = "Payload to update action")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class UpdatePolicyRequest {
    public static final String SERIALIZED_NAME_STATEMENTS = "statements";

    @SerializedName(SERIALIZED_NAME_STATEMENTS)
    private List<PolicyStatement> statements = new ArrayList<>();

    public UpdatePolicyRequest() {}

    public UpdatePolicyRequest statements(List<PolicyStatement> statements) {

        this.statements = statements;
        return this;
    }

    public UpdatePolicyRequest addStatementsItem(PolicyStatement statementsItem) {
        this.statements.add(statementsItem);
        return this;
    }

    /**
     * Get statements
     *
     * @return statements
     */
    @javax.annotation.Nonnull
    @ApiModelProperty(required = true, value = "")
    public List<PolicyStatement> getStatements() {
        return statements;
    }

    public void setStatements(List<PolicyStatement> statements) {
        this.statements = statements;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UpdatePolicyRequest updatePolicyRequest = (UpdatePolicyRequest) o;
        return Objects.equals(this.statements, updatePolicyRequest.statements);
    }

    @Override
    public int hashCode() {
        return Objects.hash(statements);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class UpdatePolicyRequest {\n");
        sb.append("    statements: ").append(toIndentedString(statements)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}
